name: Deploy to Linux Server

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Build the project
      run: pnpm build

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/github_deploy_key
        chmod 600 ~/.ssh/github_deploy_key
        cat >>~/.ssh/config <<END
        Host ops
          HostName $SSH_HOST
          User $SSH_USERNAME
          IdentityFile ~/.ssh/github_deploy_key
          StrictHostKeyChecking no
        END
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}


    - name: Compress files
      run: tar -czvf output.tar.gz ./.output ./ecosystem.config.cjs

    - name: Copy files via SCP
      run: |
        scp output.tar.gz ops:/maher/portfolio

    - name: Extract files on the server
      run: |
        ssh -tt ops 'bash -ic "rm -rf /maher/portfolio/.output && tar -xzvf /maher/portfolio/output.tar.gz -C /maher/portfolio && rm /maher/portfolio/output.tar.gz"'

    - name: Ensure PM2 process is running
      run: |
        ssh -tt ops 'bash -ic "cd /maher/portfolio && pm2 start ecosystem.config.cjs --update-env"'